services:
  espnet:
    build: .
    container_name: espnet
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./egs:/espnet/egs
      - ./egs2:/espnet/egs2
      - ./espnet:/espnet/espnet
      - ./espnet2:/espnet/espnet2
      - ./utils:/espnet/utils
      - ./test:/espnet/test
      - ./tools:/espnet/tools
      - /dev/shm:/dev/shm
    working_dir: /espnet
    command: /bin/bash
    tty: true
