use_amp: true

lm: transformer
lm_conf:
    pos_enc: null
    embed_unit: 128
    att_unit: 512
    head: 4
    unit: 2048
    layer: 6
    dropout_rate: 0.1

grad_clip: 5.0
batch_type: numel
batch_bins: 500000         # Good throughput on V100
accum_grad: 1
max_epoch: 40

optim: adam
optim_conf:
    lr: 0.002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 2000

best_model_criterion:
  - [valid, loss, min]
keep_nbest_models: 5

# DDP
ngpu: 8
num_workers: 4

# Enable DistributedDataParallel
use_ddp: true
